### ISSUE TITLE
[bug] Having a lot of trouble with plugin

### ISSUE THREAD

**Issue by schrammalama** [CameronRedmore/memory-deck#2]
The only game I've gotten to return any values was Super Mario World via retroarch. There were two things I tried to get, the first was my X coordinates. I started with a search for any value and narrowed it down by moving back and forth, staying in the same place, etc. I finally got under 10 values but when I went down to edit it there were no values there. The second thing I tried was to change the time value. The level started with 300 on the clock, I paused and entered 300, it said how many values there were, I un paused let it count down 10, paused and chose decreased by 10. It then said 0 results. I reset and tried again, entered the time, gave me results, I unpaused, selected just decreased and 0 results. This happened no mater what I chose after the initial results. I also tried Terraria, native and Mario Odyssey, yuzu. Even when choosing Any when searching it returns 0 results. I looked it up and for yuzu on cheat engine you have to turn on mem_mapped. I am completely lost.

**Comment by HeyItsWaters** [comment]
@schrammalama  It looks like you had a couple of issues with this plugin - can you see if the newest version works for you?

Should be version 0.1.2

**Comment by HeyItsWaters** [comment]
@schrammalama 
It looks like you have a couple different issues, let me try and address them individually.

`I finally got under 10 values but when I went down to edit it there were no values there.`
I had a similar issue with version 0.1.1 of this plugin - I submitted a Pull Request and got the plugin updated to 0.1.2 with a code change that fixed this issue for me, can you check if 0.1.2 resolves this for you?

`It then said 0 results`
This may be similar to Issue #7 - this plugin searches memory for literal numbers, and some games obfuscate these numbers in memory to try and defeat this type of cheating. I'm sure this is true even for games being run in an emulator. For these types of values, your best bet is doing "fuzzy searching" as I described in Issue #7.
> Search for all values, do something in the game to manipulate the value you want to edit (such as spending coins or selling something and gaining coins) then searching for values that have increased or decreased.
