### ISSUE TITLE
[feature request] .CT support

### ISSUE THREAD

**Issue by LhymeFruit** [CameronRedmore/memory-deck#20]
no other program for it

**Comment by HeyItsWaters** [comment]
@omnom143 I don't know what you're asking for, please add more details.

**Comment by LhymeFruit** [comment]
> @omnom143 I don't know what you're asking for, please add more details.

.Ct files or cheat table files are the files used by cheat engine sometimes using gui

**Comment by HeyItsWaters** [comment]
I see - I looked around to see what .ct files were and it looks like they are specifically meant for Cheat Engine.

While this memory-deck plugin behaves in a similar way, it doesn't understand what .ct files are. I already have a feature request open for being able to load/save memory addresses, similar to what you're asking for over in issue #16 

Currently this functionality is beyond my skill level, but if you'd like to contribute, feel free to submit a PR.


Thanks!
