### ISSUE TITLE
[bug] straight up not working

### ISSUE THREAD

**Issue by LhymeFruit** [CameronRedmore/memory-deck#21]
im having a lot of issues on multiple games on the latest and second to latest updates
-it not showing any numbers at all
-sometimes doesnt even show the process
-too many processes to identify

**Comment by HeyItsWaters** [comment]
@omnom143 there's a lot to unpack here.

So you're saying sometimes it shows too many processes, and sometimes none. If you can provide more information or what you think would be better, I look forward to it.
Currently, it gets the full process list of everything running under the "deck" user, and then there's a list of processes we ignore. It's possible we should add more to that, or the opposite and prune it.

If you can provide some constructive feedback on that front I'd appreciate it.

As for "it not showing any numbers at all", you mean when you search for a value there are 0 results?

I've successfully used every version of this plugin on multiple games, so if you can provide the actual game and correlating issue that might be more useful.

**Comment by LhymeFruit** [comment]
> @omnom143 there's a lot to unpack here.
> 
> So you're saying sometimes it shows too many processes, and sometimes none. If you can provide more information or what you think would be better, I look forward to it. Currently, it's gets the full process list of everything running under the "deck" user, and then there's a list of processes we ignore. It's possible we should add more to that, or the opposite and prune it.
> 
> If you can provide some constructive feedback on that front I'd appreciate it.
> 
> As for "it not showing any numbers at all", you mean when you search for a value there are 0 results?
> 
> I've successfully used every version of this plugin on multiple games, so if you can provide the actual game and correlating issue that might be more useful.

yes 0 results

**Comment by HeyItsWaters** [comment]
@omnom143  

I can't possibly test this plugin on every value in every game - but if you mention the game and value you are trying to modify, others may be able to chime in on whether they were successful or if it's not possible for that specific game.
(Some games obfuscate in-game values in the process memory, in which case you may not be able to use this plugin in its current state.)

Simply saying "it doesn't work" doesn't help me or you or anybody else looking at this issue. I don't mean to offend, I just need more information.

Thanks!
