### ISSUE TITLE
[feature request] add ability to freeze addresses

### ISSUE THREAD

**Issue by RyuSeisuke1992** [CameronRedmore/memory-deck#22]
Very often it happens that values cannot be edited permanently. Freezing values or addresses could cause this problem that the value cannot be reset. If you freeze a address the address will not change until you unfreeze it. The value does change but memorydeck will restore the value to its frozen state every few milliseconds.

**Comment by HeyItsWaters** [comment]
There are a couple ways to go about this, both of which scare me a little bit.

The plugin itself uses [scanmem](https://github.com/scanmem/scanmem/) as the backend.

- Option 1.) There's actually kind of a way to do this natively in scanmem (see [here](https://www.mankier.com/1/scanmem#Commands-set)) however I would have to spin this off into a subprocess and keep track of it so we could allow the user to stop it somehow, and also not let them lock up the Deck.
- Option 2.)  Similarly to Option 1, using the `set` command, manage the "delay" manually and still background a subprocess.

Right now this is a little beyond my skill level, but I do think it's a totally legitimate enhancement.

Thanks!

**Comment by HeyItsWaters** [comment]
once merged, this feature enhancement will be implemented with v0.1.9
