### ISSUE TITLE
Broken on steamos preview build

### ISSUE THREAD

**Issue by coverton341** [CameronRedmore/memory-deck#24]
Since last week, when steam put out an update to the preview and beta channels several decky plugins lost functionality, memory deck included.
Nothing works at all, only an empty screen is pulled up upon attempting to run memory deck.

**Comment by HeyItsWaters** [comment]
@coverton341 i think there were a couple issues on the Decky side that needed to be fixed, and all we need to do here is bump up the decky-frontend-lib package that is pulled in for the individual plugins.

The latest merge does this, gonna get the ball rolling on getting this update into the Test/Main Deck store.
