### ISSUE TITLE
Exiting quick access menu resets search

### ISSUE THREAD

**Issue by schrammalama** [CameronRedmore/memory-deck#3]
It was working fine until all of a sudden after I run a search then go back into the game to for example change the number of items in my inventory, when I go back to narrow my search by entering the new value I find that my search has been reset.

**Comment by My1** [comment]
same here

**Comment by tuftman-0** [comment]
I'm still having this issue with decky v2.5.3-pre3 and memory deck 0.1.3
edit: nevermind, it only happens when you back out of the memory deck tab, not when you close the QAM.

**Comment by HeyItsWaters** [comment]
@tuftman-0 thanks for the update - this was an issue before I started taking over the plugin, so wasn't even sure where to look at fixing this or testing it haha.
