### ISSUE TITLE
Tool wont show opened process

### ISSUE THREAD

**Issue by Tronus1409** [CameronRedmore/memory-deck#30]
Hi i have the Problem that i dont have any processes in the list, even after refreshing

**Comment by HeyItsWaters** [comment]
@lITronusIl I recommend uninstalling the plugin and installing version 0.1.5 - there's a known issue with 0.1.6

**Comment by HeyItsWaters** [comment]
v0.1.6 has been pulled from the store - once the Decky team fixes the build pipeline stuff this should be resolved.
