### ISSUE TITLE
[BUG] Cant edit Results

### ISSUE THREAD

**Issue by Tronus1409** [CameronRedmore/memory-deck#37]
Hi, after scanning 2 times, it wont let me edit anything, please fix that.
![20230518_145610](https://github.com/CameronRedmore/memory-deck/assets/67700256/d4dcb068-9f78-4f19-9001-6ab1ef38aa6a)

**Comment by HeyItsWaters** [comment]
@lITronusIl  hey there, it looks like you don't have 10 or less results, so it won't show them to you.

By default this plugin will only show you the actual results (and edit them) if there are 10 or less results.

You'll need to narrow down your result set first. This is mentioned in the main README on this GitHub repo.
