### ISSUE TITLE
RedDeadRedemption2 

### ISSUE THREAD

**Issue by splatchoot** [CameronRedmore/memory-deck#39]
Hello
i first searched for the value of the ammount of dollars i had, there was a lot of matches, but then if i search a second time when the value has decreased, it doesn't find any value

**Comment by HeyItsWaters** [comment]
@splatchoot I know you posted the same thing in the Discord, however I wanted to copy/paste that info here in case someone else looks for this.

It sounds like RDR2 might be obfuscating the money value in memory. Try searching for all values, then increasing/decreasing the money in game and searching for increases/decreases instead.

**Comment by splatchoot** [comment]
> @splatchoot I know you posted the same thing in the Discord, however I wanted to copy/paste that info here in case someone else looks for this.
> 
> It sounds like RDR2 might be obfuscating the money value in memory. Try searching for all values, then increasing/decreasing the money in game and searching for increases/decreases instead.

i appreciate the help, but i ended up finding a way to install mods, so i can give myself as much money as i want with RAMPAGE mod
