### ISSUE TITLE
No processes detected

### ISSUE THREAD

**Issue by raspgalax** [CameronRedmore/memory-deck#40]
It just says Process Selection then the Reload Process List button. There's no option to select a Process no matter what I loas

**Comment by onlurking** [comment]
Can confirm that this bug happens in a Steam Deck that received a factory reset in the past two weeks.

**Comment by HeyItsWaters** [comment]
@dmbromley @onlurking 

I'm on SteamOS 3.5 running DeckyLoader 2.10.0 and was able to uninstall/reinstall the plugin (v0.1.7-1) and then use it successfully.

If you are having issues, please include the SteamOS version as well as the DeckyLoader & plugin versions.

SteamOS version
DeckyLoader version
Plugin version
Game

Thanks!

**Comment by raspgalax** [comment]
@HeyItsWaters @onlurking 
Decky Version is v2.10.0
Memory Deck 0.1.7-1
SteamOS Holo 3.4.8

Humankind / Vampire Survivors/ Yakuza Like A Dragon

I reinstalled and it still just says Reload Process List unfortunately

**Comment by onlurking** [comment]
@HeyItsWaters 

Decky Version is v2.10.1
Memory Deck 0.1.7-1
SteamOS Holo 3.4.8
Happens with any game.

But also switched to the Main Branch and upgraded the SteamOS up to 3.5 as well and the bug is still happening, only shows `Reload Process List` with no processes in sight.

**Comment by HeyItsWaters** [comment]
I happen to have one of those games and I'm on the same versions and it works for me.

The only thing I can recommend is uninstalling memory-deck, reinstalling DeckyLoader, and then installing the plugin again.

The only actual troubleshooting we could do will require y'all to set up SSH and run the plugin manually while the game is running, and I don't have written instructions on how to do this.

**Comment by raspgalax** [comment]
On the latest Decky it works now! On something like Humankind where you have a gold value, do you keep the search type as == and the value type as Auto? I keep telling it the new values, and after three searches it goes down to 0 results each time.

**Comment by HeyItsWaters** [comment]
Yes that is correct. Some games obfuscate their values in memory, though, so you might try doing a fuzzy search instead.

Search for all, change your value in game, then do a search for an increase or decrease.

**Comment by raspgalax** [comment]
When searching for all, it crashes the machine and the screen just goes black until you do a hard power off and on.

**Comment by HeyItsWaters** [comment]
Sounds like doing memory modification to that game with this plugin in its current state isn't possible, sorry about that.
