### ISSUE TITLE
Decky reports plugin need to fit new steam ui

### ISSUE THREAD

**Issue by 403page** [CameronRedmore/memory-deck#41]
After updating steam client with new steam ui, memory deck cannot be opened on my steamdeck, and it reports this plugin need to fit new steam ui.

**Comment by HeyItsWaters** [comment]
@403page Please provide SteamOS version, DeckyLoader version, and plugin version.

Thanks!

**Comment by 403page** [comment]
@HeyItsWaters
Steamos version 3.4.8
Steam version 1686880776
Deckyloader v2.10.0
Memory deck 0.1.7-da377b8
![IMG_0135](https://github.com/CameronRedmore/memory-deck/assets/49970397/2fb1ef89-ad7d-4500-ac77-6d96f942b484)
![IMG_0151](https://github.com/CameronRedmore/memory-deck/assets/49970397/ec1daf3a-dd89-4442-94c0-c103eb0b136d)
![IMG_0152](https://github.com/CameronRedmore/memory-deck/assets/49970397/695f4704-ec7d-4e5a-b3a5-b58e491b4ab8)

Cannot copy error msg from steamdeck, sorry for using iPad camera, please let me know if more info needed, thanks!

**Comment by HeyItsWaters** [comment]
@403page there should be a newer memory-deck version than that. You might need to flip over to the pre-release channel in DeckyLoader to see it.

I think it's 0.1.7-1

**Comment by 403page** [comment]
@HeyItsWaters Switched to default channel and found this version, and it works perfectly without this issue, thank you!
