### ISSUE TITLE
Search results never populate/plugin freezing/undetected processes

### ISSUE THREAD

**Issue by Ve99ies** [CameronRedmore/memory-deck#42]
Plugin often refuses to produce search results or has no processes detected. Reloading the plugin resolves the issue temporarily. 

I'm using the latest version of steam deck os, decky loader, and the plugin. 

After about 4 times of searching values the search either displays the loading symbol and never produces results or it just says zero and never updates even if you reset the search. 

Also sometimes it will not display the process even though the game is running. 

Reloading/reinstalling the plugin fixes it temporarily but the bug reoccurs frequently.

I have yet to get the plugin to correctly detect or change a single desired value. 

I tried it for several games so far and have had no luck with any of them. 

The most recent two were resident evil 4 (2008)

And blasphemous. 

Resident evil I just tried doing pistol ammo. The values when I didn't experience the bugs I described above narrowed down but after I got to two values I edited them and they never were reflected in game as being changed. 

For blasphemous I had a similar experience. 
Using increased search option after searching an initial value narrowed results untill they were lower then 10 in number. I edited all the values and the change was never reflected. 
For this game you get a number of points for upgrades and I was trying to edit them to a high number to unlock all the attacks and specials. 

Other games I've tried have been devil may cry series and bioshock series. I also tried the borderlands games. Had no success with anything so far. I really would like this to work as using cheat engine on Linux requires some hoop jumping I don't want to do. 

I have also tried uninstalling and reinstalling decky loader and the plugin it's self. No luck.

**Comment by ricksanchez6969** [comment]
Huh, for me it doesn't work at all now. It says there's an error loading Memory Deck, and that it possibly just needs to be updated to the latest SteamOS update or something like that

**Comment by Zune-Ahmed** [comment]
> Huh, for me it doesn't work at all now. It says there's an error loading Memory Deck, and that it possibly just needs to be updated to the latest SteamOS update or something like that

Mine just don't populate the process list at all.

**Comment by Ve99ies** [comment]
> > Huh, for me it doesn't work at all now. It says there's an error loading Memory Deck, and that it possibly just needs to be updated to the latest SteamOS update or something like that
> 
> Mine just don't populate the process list at all.

I finally got it to work for a game called code vein, but it's the only game I've gotten it to work on. Still had all the issues with it crashing and not populating process list but once I finally got thru all that I had some minor success changing a few items values. 

I've tried it in about 20 games since this post and it only worked in one of them. 

I think the plugin is just extremely basic and doesn't work for most circumstances. I even tried it for very simple pixel games and it couldn't detect values a lot of the time. 

I understand some games use a form of masking to hide values to prevent cheating or people copying their coding style but I doubt this is true for over 25 games in my library. I think the plugin probably has some issues. Then again it's just one or two people that made it and it's not something that is funded. It was just a labor of love.

**Comment by HeyItsWaters** [comment]
Hey @Ve99ies - I just submitted a request to update the plugin to 0.1.8 that might help with some of the issues you are facing.

Unfortunately, you hit the nail on the head with your last sentence. It's just me and Cam, and Cam doesn't even have a Steam Deck anymore LOL

I'm going to try and get back in the swing of things and actually maintain this plugin, it's just tough since there are SO many games out there, a lot of which use memory obfuscation (so this plugin likely would never work for those games) and it's really disheartening to have folks only complain about it not working in games, only to find out it's just not possible.

Again, I'm trying to get back into things and hopefully will have some time to make some updates for this plugin soon.

Thanks!

**Comment by HeyItsWaters** [comment]
v0.1.8 is available in the test Decky store - it seems to resolve a lot of issues folks have been having, so please give that a shot.

it should hit the production Decky store soonish - let me know if you still have these issues after upgrading and we can re-open this issue.
