### ISSUE TITLE
Usage with Linux native games

### ISSUE THREAD

**Issue by colpocleisis** [CameronRedmore/memory-deck#43]
Hi, first of all thank you for this plugin.
Here's my question (maybe I'm just dumb) but the plugin doesn't seems to be working with Linux native games. I have tried with Dead Cells and Slay the Spire both times there's a single process to choose (./dead cells or ./slaythespire) but when you try to find any kind of values it always returns 0 results (even if you do an unknown initial value search such that it should scan all values it still returns 0 results). Any way to get it working?

**Comment by colpocleisis** [comment]
I'm dumb, this solved the issue

https://github.com/CameronRedmore/memory-deck/issues/8#issuecomment-1406404836

**Comment by HeyItsWaters** [comment]
You're not dumb, I have a code change that will force this plugin to run as root to avoid this issue in the future I just haven't pushed it out yet.
