### ISSUE TITLE
Build instructions in the README file

### ISSUE THREAD

**Issue by Vortelf** [CameronRedmore/memory-deck#50]
Hello,

I was in a hurry to get the new version with DFL, so I built it myself, and I thought that maybe other people might find this helpful too if it's available in the README.

Here's my way of doing it, some adjustments may be needed. If a Dockerfile is present for building the `index.js`, it might also simplify things for some folks.

```
# npm is required
> npm i -g rollup
# install dependencies with npm|yarn|pnpm
> yarn install
# build frontend
> yarn run build
---
# transfer to deck (optional)
> scp dist/index.js deck@DECK_LOCAL_IP:/home/deck/homebrew/plugins/memory-deck/dist/index.js
```
Obviously, this is only for the frontend part (as currently it's the only thing updated) but you should get the gist.

**Comment by HeyItsWaters** [comment]
I assume the new version worked for you then? 


yes I agree that we need those instructions in the wiki, which I plan on adding at some point. I am also planning on hosting a version of the scannem .so file somewhere already compiled.


lots of ambitions and good intentions, just gotta find the time.

**Comment by Vortelf** [comment]
> I assume the new version worked for you then?

Yes, it works just like it used to.

**Comment by HeyItsWaters** [comment]
@Vortelf  I went ahead and created an initial wiki that has this info, thanks for providing the steps and letting me know the latest code works for you!
https://github.com/CameronRedmore/memory-deck/wiki

Let me know via this issue if you think it should be updated moreso. This was a first attempt at throwing some basic info into a page.
