### ISSUE TITLE
Memory deck plugin didn’t work properly.

### ISSUE THREAD

**Issue by iOS4all** [CameronRedmore/memory-deck#7]
As the title said. This plugin is basically a game memory editor to change the value.
I tried all three versions which is 1.0 , 1.1 and 1.2 but unfortunately no luck. Any help please?

**Comment by HeyItsWaters** [comment]
What game are you using the plugin on?

Can you describe the actual issue you are having? Does the plugin itself not show up? Does the process list not load?

Need more info before anyone can help.

**Comment by iOS4all** [comment]
I tried Sky force reloaded it searches for the specific value and it’s appear but when I want to change the value to another number nothing happened.

Also I tried Sentinel 3 but unfortunately it doesn’t show any value whatever I put nothing happen.

if you have a discord I can send you some videos for the issues that I mentioned above.

**Comment by Mte90** [comment]
I tested with Tropico 5 and with other games but doesn't work.
I tried also with values like 0 or just starting the scan but nothing is happening.

There is a log somewhere that I can share to help debugging?

**Comment by Mte90** [comment]
Investigated a bit, if I use steamtinkerlaunch it is able to find the right process and start scanning.
Instead without i find just a path for the. Steam folder and doesn't search.
![IMG_20221223_224859.jpg](https://user-images.githubusercontent.com/403283/209408276-f4209b92-be7f-4f71-a206-9c1c800415ef.jpg)

**Comment by HeyItsWaters** [comment]
> I tested with Tropico 5 and with other games but doesn't work. I tried also with values like 0 or just starting the scan but nothing is happening.
> 
> There is a log somewhere that I can share to help debugging?

I don't think this plugin logs anything anywhere at the moment - however you should be able to SSH into your SteamDeck while your game is running and use the Konsole to run memory-deck instead. (This is how I discovered an issue I had a few weeks ago with the plugin)

If you want to try this ^ hit me up in Discord and I can walk you through it. Since I don't have the game I don't know what part the plugin is failing on. (In the Steam Deck Homebrew discord, there is a plugin-forum channel, with a Memory Deck Support subchannel)

> Investigated a bit, if I use steamtinkerlaunch it is able to find the right process and start scanning.
> Instead without i find just a path for the. Steam folder and doesn't search.

That's interesting - I've never used that wrapper before...every game I launch from the default Steam Launcher has shown up in the process list so far.

**Comment by HeyItsWaters** [comment]
> I tried Sky force reloaded it searches for the specific value and it’s appear but when I want to change the value to another number nothing happened.
> 
> Also I tried Sentinel 3 but unfortunately it doesn’t show any value whatever I put nothing happen.
> 
> if you have a discord I can send you some videos for the issues that I mentioned above.

If you're in the Steam Deck Homebrew discord, you can find me under HeyItsWaters. There has been some discussion about how some games will hide true values or obscure them, so that memory editors like this plugin just won't work. This may be the case for you...

**Comment by iOS4all** [comment]
> > I tried Sky force reloaded it searches for the specific value and it’s appear but when I want to change the value to another number nothing happened.
> > Also I tried Sentinel 3 but unfortunately it doesn’t show any value whatever I put nothing happen.
> > if you have a discord I can send you some videos for the issues that I mentioned above.
> 
> If you're in the Steam Deck Homebrew discord, you can find me under HeyItsWaters. There has been some discussion about how some games will hide true values or obscure them, so that memory editors like this plugin just won't work. This may be the case for you...

Unfortunately I didn’t see you. Please can you give your invitation by sharing your username in discord? Or just add me.
My username is: Mo0ody#4912
Because I want to show you the process of this plugin also to solve the issue step by step by your guide.

**Comment by HeyItsWaters** [comment]
@iOS4all 
I know we didn't necessarily resolve the issues you are having over on Discord, but I think you are running into an inherent flaw with memory editing - some games obfuscate the values. You may see that you have 139 coins in the game, but in reality that number might not exist in memory as 139.

I recommend you try fuzzy searching instead. Search for all values, do something in the game to manipulate the value you want to edit (such as spending those coins or selling something) then searching for values that have increased or decreased. This still may not work, but I believe the plugin is still behaving as designed.


@Mte90 
Make sure you're on version 0.1.2 - if you're still having issues please open a new issue and include as much details as possible. Thanks!
